# site settings
title: Jim Harris
subtitle: by HTML5 UP
email: jgbharris@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: https://jgbharris.github.io
url: https://jgbharris.github.io
author:
street_address:
city:
state:
zip_code:
country:
phone:

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/jgbharris

# build settings
markdown: kramdown

sass:
  style: compressed
